### PR TITLE
feat: improve messages in response

### PR DESCRIPTION
**Pull request by paupm**
Keep the same message for the response and use `acked` as a boolean to indicate whether the result is successful or not.

Proposed message interface

```
type Message struct {
	Id    interface{}
	Body  []byte
	acked *bool
}
```

Note that `acked` is now a pointer to a bool variable, that pointer will be `nil` in the request flow, and point to a true|false value in the response.

### CODE REVIEW

**Comment by paupm** [comment]
I have modified locally the [hp-passthrough](https://github.com/softonic/hp-passthrough/) middleware to test, and verified the Body can be deserialised properly
image

**Comment by mindhells** [comment]
does this fix #23 ?

**Comment by paupm** [comment]
> does this fix #23 ?

yes, it is already linked

**Review by joskfg — APPROVED** [review]

**Review by bvis — APPROVED** [review]
🥇

**Pull request merged**
